### ISSUE TITLE
Failed to install launcher

### ISSUE THREAD

**Issue by fsl3118** [an-anime-team/the-honkers-railway-launcher#58] opened 2023-07-26 03:23 UTC
I read the wiki and copied the command to my terminal, but there's still something wrong, but I don't know how to add "org.gnome.Platform/x86_64/43".
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/134755278/c960ae18-a56a-4ab1-bec3-8f50124f93eb)

**Comment by krypt0nn** [comment] 2023-07-26 10:13
Duplicate of #13

**Closed** 2023-07-26 10:14 UTC
