### ISSUE TITLE
"using this tool with HSR is unsafe. Refer to readme for more details" 

### ISSUE THREAD

**Issue by Phongvngg1** [an-anime-team/the-honkers-railway-launcher#39] opened 2023-06-17 16:22 UTC
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/87188286/cdb9e8db-7cac-4087-9f44-587dd20af89f)
i cant start game, what to do ?

**Comment by krypt0nn** [comment] 2023-06-17 16:24
Duplicate of #35

**Closed by krypt0nn** 2023-06-17 16:24 UTC
