### ISSUE TITLE
Display "using this tool with HSR is unsafe" and can't enter the game.

### ISSUE THREAD

**Issue by Jason-summer** [an-anime-team/the-honkers-railway-launcher#46] opened 2023-06-21 04:53 UTC
I can't get into the game, every time I click 'Launch' it pops up with this. Has anyone else experienced the same situation?  
"using this tool with HSR is unsafe"

一直进不了游戏，每次点击“启动”就会弹出这个，有谁有遇到过同样的情况吗？

![截图 2023-06-21 12-47-45](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/30980467/f28aa60b-3860-4f01-86e9-775f45e04a87)
![截图 2023-06-21 12-49-55](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/30980467/22e0e71a-a048-4ffc-b2f7-d8927fc5dd3a)

**Comment by krypt0nn** [comment] 2023-06-21 05:58
Duplicate of #35

**Closed** 2023-06-21 05:58 UTC
