### ISSUE TITLE
Jadeite Autopatcher giving error

### ISSUE THREAD

**Issue by danielshamsudin** [an-anime-team/the-honkers-railway-launcher#37] opened 2023-06-16 18:49 UTC
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/63139460/3bc11440-71bb-4ce9-a57e-9170d57abb21)

**Comment by krypt0nn** [comment] 2023-06-16 18:58
Duplicate of  #35

**Closed by krypt0nn** 2023-06-16 18:58 UTC
